### ISSUE TITLE
Grumphp version compatibility (0.17.2)

### ISSUE THREAD

**Issue by ralkeon** [prudloff-insite/grumphp-phpcbf#1]
The current grumphp version is the 0.17.2, when I try to install grumphp-phpcbf via composer I receive a requirement error:
```
Problem 1
    - Installation request for insite/grumphp-phpcbf ^0.1.1 -> satisfiable by insite/grumphp-phpcbf[0.1.1].
    - insite/grumphp-phpcbf 0.1.1 requires phpro/grumphp ^0.16.2 -> satisfiable by phpro/grumphp[v0.16.2] but these conflict with your requirements or minimum-stability.
```
It still works with the new grumphp version, I tested.
Can this be updated?

**Comment by prudloff-insite** [comment]
Hello,
Thanks for the report. I changed the requirement.

**Comment by ralkeon** [comment]
Can you create a new release? so we can install with composer :)

**Comment by prudloff-insite** [comment]
I published a new tag.
